<a href="https://colab.research.google.com/github/91Tommy/data-science-try/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [4]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [5]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [6]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p-q)

np.float64(5.0)

In [7]:
np.set_printoptions(precision=4, suppress=True)


In [9]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [10]:
A = np.array([[2,4], [1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [11]:
B = np.array([[10, -1]])
B

array([[10, -1]])

In [13]:
A_inv=np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [17]:
AA = np.squeeze(np.asarray(A_inv))
BB = np.squeeze(np.asarray(B))
X=np.dot(AA,BB)
X

array([1., 2.])

In [18]:
X.shape

(2,)