<a href="https://colab.research.google.com/github/91Tommy/data-science-try/blob/main/01_wprowadzenie/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

Tablice

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [13]:
x.dtype

dtype('float64')

In [17]:
x =np.array([[1, 2],[-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [18]:
x = np.array([[1,2,3], [4,2,1]])
x

array([[1, 2, 3],
       [4, 2, 1]])

Typy danych

Tworzenie tablic

In [19]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(start=10, stop=100, step=5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [28]:
np.linspace(start=0, stop=1000, num=100, dtype='int')

array([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90,  101,
        111,  121,  131,  141,  151,  161,  171,  181,  191,  202,  212,
        222,  232,  242,  252,  262,  272,  282,  292,  303,  313,  323,
        333,  343,  353,  363,  373,  383,  393,  404,  414,  424,  434,
        444,  454,  464,  474,  484,  494,  505,  515,  525,  535,  545,
        555,  565,  575,  585,  595,  606,  616,  626,  636,  646,  656,
        666,  676,  686,  696,  707,  717,  727,  737,  747,  757,  767,
        777,  787,  797,  808,  818,  828,  838,  848,  858,  868,  878,
        888,  898,  909,  919,  929,  939,  949,  959,  969,  979,  989,
       1000])

Operacje na tablicach

In [29]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [30]:
A+B

array([6, 0, 7, 4])

In [31]:
A+3

array([6, 4, 7, 5])

In [32]:
A+3*B

array([12, -2, 13,  8])

In [34]:
np.add(A,B)

array([6, 0, 7, 4])

In [35]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [36]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [37]:
X*Y

array([[6, 0],
       [2, 0]])

In [38]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [39]:
np.random.seed(0)

In [40]:
np.random.randn()

1.764052345967664

In [41]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [42]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [43]:
np.random.rand()

0.1965823616800535

In [44]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [45]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [47]:
np.random.randint(10)

3

In [53]:
np.random.randint(low=10, high=101)

12

In [57]:
np.random.randint(low=10, high=101, size = 10)

array([80, 95, 41, 23, 81, 66, 34, 89, 51, 28])

In [63]:
np.random.choice([4,2,1,3])

np.int64(3)

In [64]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.random.shuffle(data)

In [66]:
data

array([2, 3, 5, 8, 0, 4, 6, 7, 1, 9])

Funkcje

In [67]:
np.exp(1)

np.float64(2.718281828459045)

In [68]:
np.all([2, 3, 1])

np.True_

In [69]:
np.any([1, 2, 3])

np.True_

In [70]:
A = np.random.rand(5)
A

array([0.22126269, 0.1412639 , 0.09725993, 0.98404224, 0.26034093])

In [71]:
np.argmax(A)

np.int64(3)

In [73]:
A[np.argmax(A)]

np.float64(0.9840422413641464)

In [74]:
np.argsort(A)

array([2, 1, 0, 4, 3])

In [75]:
np.max(A)

np.float64(0.9840422413641464)

In [76]:
np.mean(A)

np.float64(0.34083393722488087)

Indeksowanie, wycinanie

In [78]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
A[2]

np.int64(2)

In [80]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
A[0]

array([0, 1, 2, 3, 4])

Iteracje

In [82]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


Zmiana rozmiaru tablic

In [84]:
A.shape

(4, 5)

In [85]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logicze

In [87]:
A = np.arange(start=-10, stop=10, step=0.5)
A=A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [88]:
A >0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [90]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])